Update development.yml

diff --git a/.github/workflows/development.yml b/.github/workflows/development.yml
--- a/.github/workflows/development.yml
+++ b/.github/workflows/development.yml
@@ -7,15 +7,21 @@ on:
 
   workflow_dispatch:
 jobs:
-  cd:
-    runs-on: ubuntu-latest
+deploy:
+    machine:
+      image: ubuntu-2004:current
+    resource_class: medium
     steps:
-      - uses: actions/checkout@v3
-      - name: Deploy
-        # Only run this step if the branch is main
-        if: github.ref == 'refs/heads/main'
-        env:
-          deploy_url: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
-        run: |
-          curl "$deploy_url"
-   
+      - run:
+          name: Deploy API to Render
+          command: |
+            response=$(curl -s -w "%{http_code}" -o response.txt ${{ secrets.RENDER_DEPLOY_HOOK_URL }})
+            response_code=${response:(-3)}
+            if [ $response_code -eq 200 ]; then
+              echo "Deployment successful!"
+              cat response.txt  # Print the response body
+            else
+              echo "Deployment failed with response code: $response_code"
+              cat response.txt  # Print the response body
+              exit 1
+            fi
